<h1>Отчет №1.</h1>
<br>
<p>1. Изучение данных, поиск аномалий в данных и их последующая коррекция.<br>
    2. Построение аналитической отчестности по данным.
</p>
<h4>Дата: 19.01.2021</h4>

<h2>Загрузка данных</h2>

In [48]:
import pandas as pd

In [49]:
order_data1 = pd.read_csv('../data/!07&08_17_VSE.csv', encoding="cp1251", engine='python', sep=';')
order_data2 = pd.read_csv('../data/!09&10_17_VSE.csv', encoding="cp1251", engine='python', sep=';')
order_data1.head()

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,Группа3,Группа4,Тип,Номенклатура,ТипТовара,Отменено,ПричинаОтмены,Количество,Цена,СуммаСтроки,ЦенаЗакупки,МесяцДатыЗаказа,ГодДатыЗаказа,ПВЗ_код,Статус,Гео,Маржа,СуммаУслуг,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
0,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ДЕТСКИЕ КОЛГОТКИ И НОСКИ,носки,ОДЕЖДА,"МАТЭКО, НОСКИ (зелен), р. 12-14",МГТ,Нет,NaN,1,50,50,"23,1",7,2 017,901000646,Доставлен,Москва,"26,9",49,49,3,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00051334048,0,NaN
1,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ДЕТСКИЕ КОЛГОТКИ И НОСКИ,носки,ОДЕЖДА,"МАТЭКО, НОСКИ (т.син), р. 12-14",МГТ,Нет,NaN,1,50,50,"23,1",7,2 017,901000646,Доставлен,Москва,"26,9",49,49,4,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00051367351,0,NaN
2,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ДЕТСКИЕ КОЛГОТКИ И НОСКИ,носки,ОДЕЖДА,"ЗАЙКА МОЯ, НОСКИ дет., р. 14",МГТ,Нет,NaN,1,49,49,"40,96",7,2 017,901000646,Доставлен,Москва,"8,04",49,49,7,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00007611755,0,NaN
3,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ДЕТСКИЕ КОЛГОТКИ И НОСКИ,носки,ОДЕЖДА,"ЗАЙКА МОЯ, НОСКИ дет., р. 14",МГТ,Нет,NaN,1,40,40,"34,21",7,2 017,901000646,Доставлен,Москва,"5,79",49,49,1,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00014478250,0,NaN
4,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ДЕТСКИЕ КОЛГОТКИ И НОСКИ,колготки,ОДЕЖДА,"ЗАЙКА МОЯ, КОЛГОТКИ дет., р. 92-98",МГТ,Нет,NaN,1,169,169,"105,21",7,2 017,901000646,Доставлен,Москва,"63,79",49,49,9,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00001209351,0,NaN

Смотрим на первоначальный размер данных:

In [50]:
print(order_data1.shape)
print(order_data2.shape)

(797192, 38)
(876075, 38)

In [51]:
order_data = order_data1
order_data = order_data.append(order_data2, ignore_index=True)
order_data

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,Группа3,Группа4,Тип,Номенклатура,ТипТовара,Отменено,ПричинаОтмены,Количество,Цена,СуммаСтроки,ЦенаЗакупки,МесяцДатыЗаказа,ГодДатыЗаказа,ПВЗ_код,Статус,Гео,Маржа,СуммаУслуг,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
0,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ДЕТСКИЕ КОЛГОТКИ И НОСКИ,носки,ОДЕЖДА,"МАТЭКО, НОСКИ (зелен), р. 12-14",МГТ,Нет,NaN,1,50,50,"23,1",7,2 017,901000646,Доставлен,Москва,"26,9",49,49,3,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00051334048,0,NaN
1,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ДЕТСКИЕ КОЛГОТКИ И НОСКИ,носки,ОДЕЖДА,"МАТЭКО, НОСКИ (т.син), р. 12-14",МГТ,Нет,NaN,1,50,50,"23,1",7,2 017,901000646,Доставлен,Москва,"26,9",49,49,4,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00051367351,0,NaN
2,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ДЕТСКИЕ КОЛГОТКИ И НОСКИ,носки,ОДЕЖДА,"ЗАЙКА МОЯ, НОСКИ дет., р. 14",МГТ,Нет,NaN,1,49,49,"40,96",7,2 017,901000646,Доставлен,Москва,"8,04",49,49,7,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00007611755,0,NaN
3,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ДЕТСКИЕ КОЛГОТКИ И НОСКИ,носки,ОДЕЖДА,"ЗАЙКА МОЯ, НОСКИ дет., р. 14",МГТ,Нет,NaN,1,40,40,"34,21",7,2 017,901000646,Доставлен,Москва,"5,79",49,49,1,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00014478250,0,NaN
4,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",ДЕТСКИЕ КОЛГОТКИ И НОСКИ,колготки,ОДЕЖДА,"ЗАЙКА МОЯ, КОЛГОТКИ дет., р. 92-98",МГТ,Нет,NaN,1,169,169,"105,21",7,2 017,901000646,Доставлен,Москва,"63,79",49,49,9,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00001209351,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1673262,31.10.2017 23:59,02.11.2017 0:00,6005071_ES,К отгрузке,3 222,3 222,Курьерская,Наличная,Москва,КОСМЕТИКА/ГИГИЕНА,СРЕДСТВА БЫТОВОЙ ХИМИИ,кондиционеры для белья,ППКП,"BURTI, ОПОЛАСКИВАТЕЛЬ с запахом розы, (1,5 л)",МГТ,Нет,NaN,2,297,594,253,10,2 017,NaN,Доставлен,Москва,88,150,150,3,2,31.10.2017 0:00,55574953-52575355515475,109117_mu19@inbox.ru,Мария,IDL00039538654,0,NaN
1673263,31.10.2017 23:59,02.11.2017 0:00,6005071_ES,К отгрузке,3 222,3 222,Курьерская,Наличная,Москва,КОСМЕТИКА/ГИГИЕНА,СРЕДСТВА БЫТОВОЙ ХИМИИ,кондиционеры для белья,ППКП,"BURTI, ОПОЛАСКИВАТЕЛЬ с запахом лаванды, (1,5 л)",МГТ,Нет,NaN,2,281,562,253,10,2 017,NaN,Доставлен,Москва,56,150,150,2,2,31.10.2017 0:00,55574953-52575355515475,109117_mu19@inbox.ru,Мария,IDL00039538755,0,NaN
1673264,31.10.2017 23:59,03.11.2017 0:00,6005077_ES,Возврат из ПВЗ,2 564,2 564,Магазины,Безналичная,Москва,ИГРУШКИ,ИГРУШКИ ДЛЯ МАЛЬЧИКОВ,"треки, парковки",ИГРУШКИ,"HOT WHEELS, НАБОР стартовый Конструктор трасс",МГТ,Нет,NaN,1,2 564,2 564,2 233,10,2 017,23111,Возврат,Москва,331,0,0,1,0,31.10.2017 0:00,55574857-54545754565577,97117_au19@mail.ru,Дмитрий,IDL00043615553,0,NaN
1673265,31.10.2017 23:59,03.11.2017 0:00,6005089_ES,Возврат из ПВЗ,2 564,2 564,Магазины,Безналичная,Москва,ИГРУШКИ,ИГРУШКИ ДЛЯ МАЛЬЧИКОВ,"треки, парковки",ИГРУШКИ,"HOT WHEELS, НАБОР стартовый Конструктор трасс",МГТ,Нет,NaN,1,2 564,2 564,2 233,10,2 017,23111,Возврат,Москва,331,0,0,1,0,31.10.2017 0:00,55574857-54545754565577,97117_au19@mail.ru,Дмитрий,IDL00043615553,0,NaN
1673266,31.10.2017 23:59,03.11.2017 0:00,6005101_ES,Доставлен,848,848,Магазины,Безналичная,Москва,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ СОБАК,пеленки и лотки,ИНОЕ,"Пеленки EVERYDAY для животных гелевые, 60*45 с...",МГТ,Нет,NaN,2,424,848,"404,6",10,2 017,GL0285876,Доставлен,Москва,"38,8",0,0,1,2,31.10.2017 0:00,55575054-56564948515679,112109_pm21@gmail.com,Иванов,IDL00032748755,0,NaN

Как можно было заметить отображаются не все колонки. Исправим это:

In [52]:
pd.options.display.max_columns = 40

## Исследование и коррекция данных ##

Посмотрим на количество пропущенных значений по столбцам

In [79]:
order_data.isna().sum()

Дата                              0
ДатаДоставки                   1230
НомерЗаказаНаСайте                0
НовыйСтатус                       0
СуммаЗаказаНаСайте                0
СуммаДокумента                    0
МетодДоставки                   114
ФормаОплаты                     116
Регион                         9845
Группа2                      325123
Группа3                      325123
Группа4                      381269
Тип                               0
Номенклатура                      0
ТипТовара                    325123
Отменено                          0
ПричинаОтмены               1509914
Количество                        0
Цена                              0
СуммаСтроки                       0
ЦенаЗакупки                  329966
МесяцДатыЗаказа                   0
ГодДатыЗаказа                     0
ПВЗ_код                      442742
Статус                            0
Гео                               0
Маржа                        329966
СуммаУслуг                        0
СуммаДоставки                     0
НомерСтроки                       0
КоличествоПроданоКлиенту          0
ДатаЗаказаНаСайте                 0
Телефон_new                       0
ЭлектроннаяПочта_new          26533
Клиент                          431
ID_SKU                            0
ГородМагазина                     0
МагазинЗаказа               1663538
dtype: int64

Рассмотрим числовые показатели 
* СуммаЗаказаНаСайте
* СуммаДокумента 
* Количество
* Цена 
* СуммаСтроки
* ЦенаЗакупки
* Маржа 
* СуммаУслуг
* СуммаДоставки
* КоличествоПроданоКлиенту

In [53]:
order_data.dtypes

Дата                        object
ДатаДоставки                object
НомерЗаказаНаСайте          object
НовыйСтатус                 object
СуммаЗаказаНаСайте          object
СуммаДокумента              object
МетодДоставки               object
ФормаОплаты                 object
Регион                      object
Группа2                     object
Группа3                     object
Группа4                     object
Тип                         object
Номенклатура                object
ТипТовара                   object
Отменено                    object
ПричинаОтмены               object
Количество                   int64
Цена                        object
СуммаСтроки                 object
ЦенаЗакупки                 object
МесяцДатыЗаказа              int64
ГодДатыЗаказа               object
ПВЗ_код                     object
Статус                      object
Гео                         object
Маржа                       object
СуммаУслуг                  object
СуммаДоставки               object
НомерСтроки                  int64
КоличествоПроданоКлиенту     int64
ДатаЗаказаНаСайте           object
Телефон_new                 object
ЭлектроннаяПочта_new        object
Клиент                      object
ID_SKU                      object
ГородМагазина               object
МагазинЗаказа               object
dtype: object

Следовательно, необходимо изменить типы колонок:

'Дата', 'ДатаЗаказаНаСайте' -> `datetime` 

'СуммаЗаказаНаСайте', 'СуммаДокумента', 'Маржа' -> `float`

'Цена', 'СуммаСтроки', 'ЦенаЗакупки' -> `float`

Посмотрим на 'СуммаЗаказаНаСайте' и 'СуммаДокумента'. По логике они должны быть равны, так как обозначают одно и тоже.

In [54]:
order_data[order_data['СуммаЗаказаНаСайте'] != order_data['СуммаДокумента']].shape[0]

506503

Как мы можем заметить строчек где 'СуммаЗаказаНаСайте' не равна 'СуммеДокумента' много. Чтобы не разбираться с каждым случаем отдельно мы удалим эти колонки и пересчитаем их если они понадобятся. Соотвественно в дальнейшем мы будем считать, что 'Цена', 'ЦенаЗакупки' и 'Количество' и 'КоличествоПроданоКлиенту' приходят к нам без ошибок (строчки где эти данные пропущены мы удалим) и все основные показатели будем пересчитывать через них.

Разберемся с доставкой. Как мы видим у доставки 'Тип' = ИНОЕ (Заметим, что только у доставки тип ИНОЕ) и пропущена 'ЦенаЗакупки'. Так как непонятно какая маржа у доставки (цена или 0), то во избежание двоякой трактовки мы исключим доставку из общего анализа (при расчете среднего чека и т.д.) и позже проанализируем данный тип отдельно.

In [55]:
order_data[order_data['Номенклатура'] == 'Доставка'].head()

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,Группа3,Группа4,Тип,Номенклатура,ТипТовара,Отменено,ПричинаОтмены,Количество,Цена,СуммаСтроки,ЦенаЗакупки,МесяцДатыЗаказа,ГодДатыЗаказа,ПВЗ_код,Статус,Гео,Маржа,СуммаУслуг,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
7,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,NaN,NaN,NaN,ИНОЕ,Доставка,NaN,Нет,NaN,1,49,49,NaN,7,2 017,901000646,Доставлен,Москва,NaN,49,49,1,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,ID10022107250,0,NaN
14,01.07.2017 0:00,14.07.2017 0:00,5031790_TR,Доставлен,1 915,1 915,Магазины,Безналичная,Сочи,NaN,NaN,NaN,ИНОЕ,Доставка,NaN,Нет,NaN,1,99,99,NaN,7,2 017,23111,Доставлен,Регионы,NaN,99,99,1,1,30.06.2017 0:00,55575656-49565651494970,107117_ku23@yandex.ru,Екатерина,ID10022107250,0,NaN
27,01.07.2017 0:00,08.07.2017 0:00,5031791_TR,Доставлен,1 218,1 218,Магазины,Безналичная,Самара,NaN,NaN,NaN,ИНОЕ,Доставка,NaN,Нет,NaN,1,99,99,NaN,7,2 017,23111,Доставлен,Регионы,NaN,99,99,1,1,30.06.2017 0:00,55575155-54535648525672,97117_au28@yandex.ru,Гость,ID10022107250,0,NaN
28,01.07.2017 0:01,04.07.2017 0:00,5031806_TR,Возврат из ПВЗ,3 089,3 089,Магазины,Безналичная,Москва,NaN,NaN,NaN,ИНОЕ,Доставка,NaN,Нет,NaN,1,49,49,NaN,7,2 017,23111,Возврат,Москва,NaN,49,49,1,1,30.06.2017 0:00,55575451-55554850515276,97117_au19@mail.ru,Наумова,ID10022107250,0,NaN
30,01.07.2017 10:01,02.07.2017 0:00,5031883_ES,К отгрузке,2 198,2 198,Курьерская,Наличная,Москва,NaN,NaN,NaN,ИНОЕ,Доставка,NaN,Нет,NaN,1,150,150,NaN,7,2 017,NaN,Доставлен,Москва,NaN,150,150,1,1,30.06.2017 0:00,55575456-55545450525776,112117_pu11@nln.ru,Павел,ID10022107250,0,NaN

Теперь надо определиться как работать с фродом. Фродом будем считать чеки, где присутствует отрицательная маржа в размере -300. Соответственно такие чеки мы удалим.

Осталось подумать, как удалить дубликаты и какие они вообще могут быть. 
Первой идеей было удалять чеки с одинаковыми товарами и статусом заказа. Однако данная идея не получила поддержки
так как ничего не мешает заказать клиенту один и тот же набор несколько раз. Поэтому было решено сделать следующее:
Удалить повторяющие строчки, только если они совпадают полностью, включая номер заказа.

### Функция подготовки данных ###
После вышеизложенного исследования данных можно сформулировать что должна делать первая функция по отчистке и подготовке данных:

* Удалить все строчки где 'Номенклатура' = 'Доставка'
* Удалить все строчки где пропущены значения в колонках 'ЦенаЗакупки', 'Цена' или 'Количество'
* Преобразовать колонки в правильный тип
* Пересчитать правильно маржу и сумму строки
* Удалить дубликаты если они есть
* Удалить фрод, то есть чеки в которых присутсвуют товары с большой отрицательной маржой
* Удалить колонки 'СуммаЗаказаНаСайте', 'СуммаДокумента' чтобы избежать неправильной трактовки в дальнейшем

In [56]:
def object_columns_to_float_columns(data, column_names):
    for column_name in column_names:
        data[column_name] = data[column_name].apply(lambda x : x.replace(',', '.'))
        data[column_name] = data[column_name].apply(lambda x : x.replace(' ', ''))
        data[column_name] = pd.to_numeric(data[column_name])
    return data

In [92]:
def prepare_data(data):
    ### TO DO: check month and years
    ### TO DO: reset_indices
    
    current_number_of_raws = data.shape[0]
    data = data[data['Номенклатура'] != 'Доставка']
    print('Количество удаленных строк, которые описывают доставку: ', current_number_of_raws - data.shape[0])
    current_number_of_raws = data.shape[0]
    data = data.dropna(subset=['Количество', 'Цена', 'ЦенаЗакупки'])
    print('Количество удаленных строк, где пропущены ключевые значения: ', current_number_of_raws - data.shape[0])
    
    data = object_columns_to_float_columns(data, ['СуммаДокумента', 'СуммаЗаказаНаСайте', 'СуммаСтроки', 'ЦенаЗакупки', 'Цена'])
    
    ### TO DO: object_columns_to_data
    
    data['СуммаСтроки'] = data['Цена'] * data['Количество']
    data['Маржа'] = (data['Цена'] - data['ЦенаЗакупки']) * data['Количество']
    data
    
    current_number_of_raws = data.shape[0]
    data = data.drop_duplicates(subset=data.columns, keep='last')
    print('Количество удаленных строк, которые были дубликатами: ', current_number_of_raws - data.shape[0])
    
    current_number_of_raws = data.shape[0]
    fraud_ids = set(data[data['Маржа'] <= -300.0]['НомерЗаказаНаСайте'].unique())
    data = data[~data['НомерЗаказаНаСайте'].isin(fraud_ids)]
    print('Количество удаленных строк, которые являются фродом: ', current_number_of_raws - data.shape[0])
    print('Количество удаленных чеков, которые являются фродом: ', len(fraud_ids))
    
    data = data.drop(columns=['СуммаЗаказаНаСайте', 'СуммаДокумента'])
    
    print('Итоговое количество строк: ', data.shape[0])
    return data

In [93]:
data = prepare_data(order_data)

# document_sums = data.groupby(['НомерЗаказаНаСайте', 'НовыйСтатус'])['СуммаСтроки'].sum().reset_index()

Количество удаленных строк, которые описывают доставку:  325123
Количество удаленных строк, где пропущены ключевые значения:  4843
Количество удаленных строк, которые были дубликатами:  2406
Количество удаленных строк, которые являются фродом:  70384
Количество удаленных чеков, которые являются фродом:  18395
Итоговое количество строк:  1270511

Проверим получилось ли у нас исправить данные:

In [ ]:
### TO DO: проверить данные

Отлично все получилось!

### Выделяем размещенные товары ###

Чтобы упростить работу с размещенными товарами оставим каждый чек по одному разу. Для этого нам нужно удалить все дубликаты с одинаковыми значениями в колонках 'НомерЗаказаНаСайте', 'Номенклатура' (Заметим, что пропущенных значений в номенклатуре нет) и 'Количество'.

In [87]:
def get_posted_goods(data):
    current_number_of_raws = data.shape[0]
    data = data.drop_duplicates(subset=['НомерЗаказаНаСайте', 'Номенклатура', 'Количество'], keep='last')
    print('Количество удаленных строк: ', current_number_of_raws - data.shape[0])
    print('Итоговых количество строк: ', data.shape[0])
    return data

In [88]:
posted_data = get_posted_goods(data)

Количество удаленных строк:  23285
Итоговых количество строк:  1247226

### Выделяем выкупленные товары

Для начала посмотрим какие значения принимает НовыйСтатус:

In [61]:
print(data['НовыйСтатус'].unique())

['Доставлен' 'Возврат из ПВЗ' 'К отгрузке' 'Отменен' 'Расформирован ПВЗ'
 'Принят в ПВЗ' 'Отменяется' 'Частичный возврат' 'Скомплектован Регион'
 'В резерве' 'Возврат' 'Отправлен в ПВЗ' 'Комплектация Регион'
 'Передан в Регион']

<p>Исходя из этих данных нетрудно понять, что заказ на пути от корзины сайта до получателя проходит достаточно длинный путь. Будем считать, что выкупленные товары это только те у которых 'НовыйСтатус' равно 'Доставлен'.<br><br>Теперь посмотрим какие значения в таком случае принимает колонка 'Отменено'.</p>

In [62]:
data[data['НовыйСтатус'] == 'Доставлен'].groupby('Отменено').size()

Отменено
Да       6666
Нет    352541
dtype: int64

<p>Как можно заметить, даже при 'НовыйСтатус' = 'Доставлен' у нас 'Отменено' может принимать значение 'Нет'. Мы считаем, что колонка 'Отменено' первична, следовательно, заказы которые доставлены, но отменены мы учитывать не будем.</p>
<p>Таким образом мы можем сделать вывод какие товары являются выкупленными:</p>

Теперь посмотрим на 'Количество' и 'КоличествоПроданоКлиенту', узнаем существуют ли варианты где они не равны

In [66]:
data[data['Количество'] != data['КоличествоПроданоКлиенту']].head()

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,МетодДоставки,ФормаОплаты,Регион,Группа2,Группа3,Группа4,Тип,Номенклатура,ТипТовара,Отменено,ПричинаОтмены,Количество,Цена,СуммаСтроки,ЦенаЗакупки,МесяцДатыЗаказа,ГодДатыЗаказа,ПВЗ_код,Статус,Гео,Маржа,СуммаУслуг,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
29,01.07.2017 0:01,04.07.2017 0:00,5031806_TR,Возврат из ПВЗ,Магазины,Безналичная,Москва,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КАНЦТОВАРЫ,"ранцы, рюкзаки, пеналы",ИГРУШКИ,"ERICH KRAUSE, РАНЕЦ раскладной Sea Woolf ( мод...",МГТ,Нет,NaN,1,3040.0,3040.0,2763.56,7,2 017,23111,Возврат,Москва,276.44,49,49,1,0,30.06.2017 0:00,55575451-55554850515276,97117_au19@mail.ru,Наумова,IDL00046097048,0,NaN
32,01.07.2017 0:22,04.07.2017 0:00,5031794_TR,Возврат из ПВЗ,Магазины,Безналичная,Москва,ОБУВЬ,ОБУВЬ ДЕТСКАЯ,резиновая обувь,ОДЕЖДА,"NORDMAN, РЕЗИНА неутепленная, (роз), р. 31/32-...",МГТ,Нет,NaN,1,310.0,310.0,238.45,7,2 017,23111,Возврат,Москва,71.55,49,49,2,0,30.06.2017 0:00,55575054-54575350505479,guest_103117_gu28@workmail.ru,Гость,IDL00046162957,0,NaN
33,01.07.2017 0:22,04.07.2017 0:00,5031794_TR,Возврат из ПВЗ,Магазины,Безналичная,Москва,ОБУВЬ,ОБУВЬ ДЕТСКАЯ,резиновая обувь,ОДЕЖДА,"ДЮНА, РЕЗИНА неутепленная, (в ассорт), р. 23-26",МГТ,Нет,NaN,1,410.0,410.0,315.00,7,2 017,23111,Возврат,Москва,95.00,49,49,1,0,30.06.2017 0:00,55575054-54575350505479,guest_103117_gu28@workmail.ru,Гость,IDL00048176149,0,NaN
42,01.07.2017 0:24,19.07.2017 0:00,5031802_TR,Возврат из ПВЗ,Магазины,Безналичная,Челябинск,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КАНЦТОВАРЫ,"ранцы, рюкзаки, пеналы",ИГРУШКИ,"ERICH KRAUSE, РАНЕЦ с эргономичной спинкой Dor...",МГТ,Нет,NaN,1,1652.0,1652.0,1180.00,7,2 017,23111,Возврат,Регионы,472.00,99,99,1,0,30.06.2017 0:00,55575348-55515057485574,114117_ru21@yandex.ru,Гость,IDL00046097149,0,NaN
49,01.07.2017 10:37,06.07.2017 0:00,5031807_TR,Доставлен,Магазины,Безналичная,Санкт-Петербург,"ТЕКСТИЛЬ, ТРИКОТАЖ",ОДЕЖДА ДЛЯ НОВОРОЖДЕННЫХ (0-2 лет),песочники,ОДЕЖДА,"LEADER KIDS, ПОЛУКОМБИНЕЗОН-песочник Морской к...",МГТ,Нет,NaN,1,125.3,125.3,120.00,7,2 017,901000646,Доставлен,Регионы,5.30,99,99,3,0,30.06.2017 0:00,55575649-56544856514878,107117_ku17@mail.ru,Анна,IDL00034067149,0,NaN

Заметим, что если 'Количество' не равно 'КоличествоПроданоКлиенту', то 'СуммаСтроки' и 'Маржа' пересчитываются по 'Количество' следовательно, чтобы исправить корректность данных, анализируя выкупленные товары, нам необходимо пересчитать их по 'КоличествоПроданоКлиенту'. Давайте сразу удалим те строки в которых 'КоличествоПроданоКлиенту' равно 0.

Таким образом чтобы выделить выкупленные товары нам нужно:
* Оставить только те строки, где 'НовыйСтатус' == 'Доставлен', а 'Отменено' == 'Нет'
* Удалить все строчки, где пропущено значение в столбце 'КоличествоПроданоКлиенту'
* Удалить все строчки, где 'КоличествоПроданоКлиенту' <= 0
* Пересчитать основные показатели через КоличествоПроданоКлиенту, а не через Количество

In [75]:
def get_purchased_goods(data):
    current_number_of_raws = data.shape[0]
    data = data[data['НовыйСтатус'] == 'Доставлен'][data['Отменено'] == 'Нет']
    print('Количество удаленных строк, где товар не доставлен или отменен: ', current_number_of_raws - data.shape[0])
    
    current_number_of_raws = data.shape[0]
    data = data.dropna(subset=['КоличествоПроданоКлиенту'])
    print('Количество удаленных строк, где пропущено значение в колонке \'КоличествоПроданоКлиенту\':', current_number_of_raws - data.shape[0])
    
    current_number_of_raws = data.shape[0]
    data = data[data['КоличествоПроданоКлиенту'] > 0]
    print('Количество удаленных строк, где \'КоличествоПроданоКлиенту\' <= 0: ', current_number_of_raws - data.shape[0])
    
    data['СуммаСтроки'] = data['Цена'] * data['КоличествоПроданоКлиенту']
    data['Маржа'] = (data['Цена'] - data['ЦенаЗакупки']) * data['КоличествоПроданоКлиенту']
    
    print('Итоговое количество строк: ', data.shape[0])
    return data

purchased_data = get_purchased_goods(data)

/Users/millb/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

Количество удаленных строк, где товар не доставлен или отменен:  744292
Количество удаленных строк, где пропущено значение в колонке 'КоличествоПроданоКлиенту': 0
Количество удаленных строк, где 'КоличествоПроданоКлиенту' <= 0:  5147
Итоговое количество строк:  521072

Проверим получившиеся данные:

In [ ]:
### TO DO: проверить данные

Отлично все получилось!

## Построение аналитической отчестности ##

Для начала, на всякий случай еще раз подготовим все данные:

In [94]:
data = prepare_data(order_data)

Количество удаленных строк, которые описывают доставку:  325123
Количество удаленных строк, где пропущены ключевые значения:  4843
Количество удаленных строк, которые были дубликатами:  2406
Количество удаленных строк, которые являются фродом:  70384
Количество удаленных чеков, которые являются фродом:  18395
Итоговое количество строк:  1270511

In [95]:
posted_data = get_posted_goods(data)

Количество удаленных строк:  23285
Итоговых количество строк:  1247226

In [96]:
purchased_data = get_purchased_goods(data)

/Users/millb/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

Количество удаленных строк, где товар не доставлен или отменен:  744292
Количество удаленных строк, где пропущено значение в колонке 'КоличествоПроданоКлиенту': 0
Количество удаленных строк, где 'КоличествоПроданоКлиенту' <= 0:  5147
Итоговое количество строк:  521072

### Основные показатели по месяцам ###
* Выручка
* Кол-во уникальных чеков
* Средний чек
* средняя цена
* Средняя маржа
* средний % маржи
* Кол-во товаров
* Кол-во уникальных клиентов
* Среднее количество товаров в чеке

In [ ]:
def get_basic_indicators(data):
    data = data.groupby(['МесяцДатыЗаказа'])['СуммаСтроки'].sum().reset_index()
    data

#### Размещенные товары ####

In [ ]:
### code

#### Выкупленные товары ####

In [ ]:
data = data.groupby

### Выкупаемость ###